website_name: Diskover AWS Deployment Guide
# Folder on the website, if you specify "folder" it will deploy this guide to https://docs.diskoverdata.com/folder
website_folder: diskover_legacy_aws_deployment_guide
# All documents need to be in shared folder
ordered_documents:
  - index_diskover_guides_header.md
  - guide_title_aws_deployment.md
  - intro_note_open_support_ticket.md
  - intro_guide_intended_for_tech.md
  - intro_tech_guides_main_intro.md
  - intro_tech_guides_aws_approved.md
  - intro_tech_guides_use_cases.md
  - intro_doc_conventions_tech.md
  - architecture_overview.md 
  - requirements_intro.md
  - requirements_aws_env_config.md
  - requirements_elasticsearch.md 
  - requirements_diskover_web.md
  - requirements_diskover_scanners.md
  - requirements_skills.md 
  - software_download.md
  - aws_env_security.md
  - install_elasticsearch_aws.md
  - install_diskover_web_aws_intro.md
  - install_diskover_web_aws_ec2_config.md
  - install_diskover_web_aws_nginx.md
  - install_diskover_web_aws_php.md
  - install_diskover_web_aws_software.md
  - install_diskover_web_launch.md  
  - install_indexers_intro.md
  - install_indexers_aws.md
  - software_activation.md
  - config_after_install.md
  - health_check_diskover_intro.md
  - health_check_diskover_web_linux.md
  - health_check_elasticsearch_linux.md
  - backup_and_recovery_intro.md
  - backup_and_recovery_setup.md
  - backup_and_recovery_elasticsearch.md
  - backup_and_recovery_indexers.md
  - backup_and_recovery_diskover_web.md
  - maintenance_routine_intro.md
  - maintenance_routine_diskover_upgrade.md
  - maintenance_routine_elasticsearch_aws.md  
  - maintenance_emergency_intro.md
  - maintenance_emergency_diskover_web.md
  - maintenance_emergency_elasticsearch_aws.md
  - aws_cost.md
  - support.md
  - contact.md
  - copyright.md
