website_name: Diskover Setup and Configuration Guide
# Folder on the website, if you specify "folder" it will deploy this guide to https://docs.diskoverdata.com/folder
website_folder: diskover_setup_and_config_guide
# All documents need to be in shared folder
ordered_documents:
  - index_diskover_guides_header.md
  - guide_title_setup_and_admin_v2.md
  - intro_guide_intended_for_tech.md
  - intro_note_open_support_ticket.md
  - intro_tech_guides_main_intro.md
  - intro_tech_guides_aws_approved.md
  - intro_tech_guides_use_cases.md
  - intro_doc_conventions_tech.md
  - architecture_overview.md 
  - requirements_intro.md
  - requirements_elasticsearch.md 
  - requirements_diskover_web.md
  - requirements_diskover_scanners.md
  - requirements_skills.md
  - software_download.md
  - system_readiness.md
  - install_checklist.md
  - install_elasticsearch.md
  - install_scanners.md
  - install_celery.md
  - install_rabbitmq.md
  - install_diskover_web.md
  - install_diskoveradmin.md
  - config_initial.md
  - create_alt_config.md
  - task_panel.md
  - backup.md
  - features_finder.md
  - config_diskoveradmin_main.md
  - config_alt_scanners.md
  - config_plugins_index.md
  - config_plugins_post_index.md
  - config_plugins_file_actions.md
  - tags.md
  - analytics.md
  - indices_management.md
  - misc_chapter.md
  - analytics_third_party.md
  - software_activation_2_3.md
  - upgrade_to_2_3.md
  - software_update_2_3.md
  - health_check.md
  - maintenance_routine.md
  - maintenance_emergency.md
  - uninstall.md
  - support.md
  - contact.md
  - copyright.md
